// Code generated by MockGen. DO NOT EDIT.
// Source: registry_http.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	gomock "github.com/golang/mock/gomock"
)

// MockHttpPort is a mock of HttpPort interface.
type MockHttpPort struct {
	ctrl     *gomock.Controller
	recorder *MockHttpPortMockRecorder
}

// MockHttpPortMockRecorder is the mock recorder for MockHttpPort.
type MockHttpPortMockRecorder struct {
	mock *MockHttpPort
}

// NewMockHttpPort creates a new mock instance.
func NewMockHttpPort(ctrl *gomock.Controller) *MockHttpPort {
	mock := &MockHttpPort{ctrl: ctrl}
	mock.recorder = &MockHttpPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHttpPort) EXPECT() *MockHttpPortMockRecorder {
	return m.recorder
}
