// Code generated by MockGen. DO NOT EDIT.
// Source: entity_name.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	gomock "github.com/golang/mock/gomock"
)

// MockEntityNameWorkflowPort is a mock of EntityNameWorkflowPort interface.
type MockEntityNameWorkflowPort struct {
	ctrl     *gomock.Controller
	recorder *MockEntityNameWorkflowPortMockRecorder
}

// MockEntityNameWorkflowPortMockRecorder is the mock recorder for MockEntityNameWorkflowPort.
type MockEntityNameWorkflowPortMockRecorder struct {
	mock *MockEntityNameWorkflowPort
}

// NewMockEntityNameWorkflowPort creates a new mock instance.
func NewMockEntityNameWorkflowPort(ctrl *gomock.Controller) *MockEntityNameWorkflowPort {
	mock := &MockEntityNameWorkflowPort{ctrl: ctrl}
	mock.recorder = &MockEntityNameWorkflowPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntityNameWorkflowPort) EXPECT() *MockEntityNameWorkflowPortMockRecorder {
	return m.recorder
}
